# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brijesh-thakkar/Desktop/DSA_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brijesh-thakkar/Desktop/DSA_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brijesh-thakkar/Desktop/DSA_Project/CMakeFiles /home/brijesh-thakkar/Desktop/DSA_Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brijesh-thakkar/Desktop/DSA_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named redis_db

# Build rule for target.
redis_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redis_db
.PHONY : redis_db

# fast build rule for target.
redis_db/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/build
.PHONY : redis_db/fast

#=============================================================================
# Target rules for targets named test_temporal

# Build rule for target.
test_temporal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_temporal
.PHONY : test_temporal

# fast build rule for target.
test_temporal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/build
.PHONY : test_temporal/fast

#=============================================================================
# Target rules for targets named test_wal_temporal

# Build rule for target.
test_wal_temporal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_wal_temporal
.PHONY : test_wal_temporal

# fast build rule for target.
test_wal_temporal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/build
.PHONY : test_wal_temporal/fast

#=============================================================================
# Target rules for targets named http_server

# Build rule for target.
http_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 http_server
.PHONY : http_server

# fast build rule for target.
http_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/build
.PHONY : http_server/fast

src/command_parser.o: src/command_parser.cpp.o
.PHONY : src/command_parser.o

# target to build an object file
src/command_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/command_parser.cpp.o
.PHONY : src/command_parser.cpp.o

src/command_parser.i: src/command_parser.cpp.i
.PHONY : src/command_parser.i

# target to preprocess a source file
src/command_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/command_parser.cpp.i
.PHONY : src/command_parser.cpp.i

src/command_parser.s: src/command_parser.cpp.s
.PHONY : src/command_parser.s

# target to generate assembly for a file
src/command_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/command_parser.cpp.s
.PHONY : src/command_parser.cpp.s

src/guard.o: src/guard.cpp.o
.PHONY : src/guard.o

# target to build an object file
src/guard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/guard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/guard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/guard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/guard.cpp.o
.PHONY : src/guard.cpp.o

src/guard.i: src/guard.cpp.i
.PHONY : src/guard.i

# target to preprocess a source file
src/guard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/guard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/guard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/guard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/guard.cpp.i
.PHONY : src/guard.cpp.i

src/guard.s: src/guard.cpp.s
.PHONY : src/guard.s

# target to generate assembly for a file
src/guard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/guard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/guard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/guard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/guard.cpp.s
.PHONY : src/guard.cpp.s

src/http_server.o: src/http_server.cpp.o
.PHONY : src/http_server.o

# target to build an object file
src/http_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/http_server.cpp.o
.PHONY : src/http_server.cpp.o

src/http_server.i: src/http_server.cpp.i
.PHONY : src/http_server.i

# target to preprocess a source file
src/http_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/http_server.cpp.i
.PHONY : src/http_server.cpp.i

src/http_server.s: src/http_server.cpp.s
.PHONY : src/http_server.s

# target to generate assembly for a file
src/http_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/http_server.cpp.s
.PHONY : src/http_server.cpp.s

src/kvstore.o: src/kvstore.cpp.o
.PHONY : src/kvstore.o

# target to build an object file
src/kvstore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/kvstore.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/kvstore.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/kvstore.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/kvstore.cpp.o
.PHONY : src/kvstore.cpp.o

src/kvstore.i: src/kvstore.cpp.i
.PHONY : src/kvstore.i

# target to preprocess a source file
src/kvstore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/kvstore.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/kvstore.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/kvstore.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/kvstore.cpp.i
.PHONY : src/kvstore.cpp.i

src/kvstore.s: src/kvstore.cpp.s
.PHONY : src/kvstore.s

# target to generate assembly for a file
src/kvstore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/kvstore.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/kvstore.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/kvstore.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/kvstore.cpp.s
.PHONY : src/kvstore.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/test_temporal.o: src/test_temporal.cpp.o
.PHONY : src/test_temporal.o

# target to build an object file
src/test_temporal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/test_temporal.cpp.o
.PHONY : src/test_temporal.cpp.o

src/test_temporal.i: src/test_temporal.cpp.i
.PHONY : src/test_temporal.i

# target to preprocess a source file
src/test_temporal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/test_temporal.cpp.i
.PHONY : src/test_temporal.cpp.i

src/test_temporal.s: src/test_temporal.cpp.s
.PHONY : src/test_temporal.s

# target to generate assembly for a file
src/test_temporal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/test_temporal.cpp.s
.PHONY : src/test_temporal.cpp.s

src/test_wal_temporal.o: src/test_wal_temporal.cpp.o
.PHONY : src/test_wal_temporal.o

# target to build an object file
src/test_wal_temporal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/test_wal_temporal.cpp.o
.PHONY : src/test_wal_temporal.cpp.o

src/test_wal_temporal.i: src/test_wal_temporal.cpp.i
.PHONY : src/test_wal_temporal.i

# target to preprocess a source file
src/test_wal_temporal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/test_wal_temporal.cpp.i
.PHONY : src/test_wal_temporal.cpp.i

src/test_wal_temporal.s: src/test_wal_temporal.cpp.s
.PHONY : src/test_wal_temporal.s

# target to generate assembly for a file
src/test_wal_temporal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/test_wal_temporal.cpp.s
.PHONY : src/test_wal_temporal.cpp.s

src/wal.o: src/wal.cpp.o
.PHONY : src/wal.o

# target to build an object file
src/wal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/wal.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/wal.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/wal.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/wal.cpp.o
.PHONY : src/wal.cpp.o

src/wal.i: src/wal.cpp.i
.PHONY : src/wal.i

# target to preprocess a source file
src/wal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/wal.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/wal.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/wal.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/wal.cpp.i
.PHONY : src/wal.cpp.i

src/wal.s: src/wal.cpp.s
.PHONY : src/wal.s

# target to generate assembly for a file
src/wal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_db.dir/build.make CMakeFiles/redis_db.dir/src/wal.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_temporal.dir/build.make CMakeFiles/test_temporal.dir/src/wal.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wal_temporal.dir/build.make CMakeFiles/test_wal_temporal.dir/src/wal.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_server.dir/build.make CMakeFiles/http_server.dir/src/wal.cpp.s
.PHONY : src/wal.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... http_server"
	@echo "... redis_db"
	@echo "... test_temporal"
	@echo "... test_wal_temporal"
	@echo "... src/command_parser.o"
	@echo "... src/command_parser.i"
	@echo "... src/command_parser.s"
	@echo "... src/guard.o"
	@echo "... src/guard.i"
	@echo "... src/guard.s"
	@echo "... src/http_server.o"
	@echo "... src/http_server.i"
	@echo "... src/http_server.s"
	@echo "... src/kvstore.o"
	@echo "... src/kvstore.i"
	@echo "... src/kvstore.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/test_temporal.o"
	@echo "... src/test_temporal.i"
	@echo "... src/test_temporal.s"
	@echo "... src/test_wal_temporal.o"
	@echo "... src/test_wal_temporal.i"
	@echo "... src/test_wal_temporal.s"
	@echo "... src/wal.o"
	@echo "... src/wal.i"
	@echo "... src/wal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

